name: BasicX
main: cc.modlabs.basicx.BasicX
version: ${version}
description: "All the basics for your minecraft paper server | Home | Warps | TPA | Vanish"
author: "LiamXSage"
api-version: "1.21"
loader: cc.modlabs.basicx.DependencyLoader
bootstrapper: cc.modlabs.basicx.CommandBootstrapper

dependencies:
  server:
    LuckPerms:
      load: BEFORE
      required: false
    PlaceholderAPI:
      load: BEFORE
      required: false
